name: Mock-App
options:
  minimumXcodeGenVersion: "2.6.0"
  bundleIdPrefix: "com.dmm.sample"
  deploymentTarget:
    iOS: "13.0"
configs:
  Debug: debug
  Staging: release
  Release: release
settings:
  base:
    SWIFT_VERSION: "5.1"
    CODE_SIGN_STYLE: "Automatic"
    TARGETED_DEVICE_FAMILY: "1"
  configs:
    Staging:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "STAGING"
packages:
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 9.0.0
  Crossroad:
    url: https://github.com/giginet/Crossroad.git
    from: 3.0.0
  CombineCocoa:
    url: https://github.com/CombineCommunity/CombineCocoa.git
    from: 0.1.0
targets:
  Common:
    type: framework
    platform: iOS
    sources:
      - path: Common
  Domain:
    type: framework
    platform: iOS
    sources:
      - path: Domain
    dependencies:
      - target: Common
    scheme:
      testTargets:
        - DomainTests
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DomainTests
    dependencies:
      - target: Domain
      - target: Mock-App
  Core:
    type: framework
    platform: iOS
    sources:
      - path: Core
    dependencies:
      - target: Common
      - target: Domain
  Mock-App:
    type: application
    info:
      path: Mock-App/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    platform: iOS
    sources:
      - path: Mock-App
    dependencies:
      - target: Common
      - target: Domain
      - target: Core
      # - package: Crossroad
    preBuildScripts:
      - name: "[SwiftLint] Run Script"
        script: "scripts/lint.sh"
    scheme:
      testTargets:
        - DomainTests
    settings:
      TARGETED_DEVICE_FAMILY: "1"
  Mock-AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Mock-AppTests
    dependencies:
      - target: Mock-App
