name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle
      uses: actions/cache@v2.0.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Setup
      run: ./scripts/setup.sh
    - name: Bootstrap
      run: ./scripts/bootstrap.sh
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.4.1.app/Contents/Developer'
    - name: Build
      run: bundle exec fastlane build
    - name: Test
      run: bundle exec fastlane tests
#     - name: Build
#       run: xcodebuild -workspace Mock-App.xcworkspace -scheme Mock-App -sdk iphonesimulator -configuration Debug build 
#     - name: Tests　ちょっとわからん...
#       run: xcodebuild test-without-building -workspace Mock-App.xcworkspace -scheme Mock-App -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3'
