name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: ./scripts/setup.sh
    - name: Bootstrap
      run: ./scripts/bootstrap.sh
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.4.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build Setting (for Xcode11 bug..)
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 
    - name: Tests
      run: swift test -v
