name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./scripts/setup.sh
    - name: bootstrap
      run: ./scripts/bootstrap.sh
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
